=== resuadam2/AD/ADTema2Ejer1/bin/Persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
<xs:element name="persona">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="nickname">
			 <xs:simpleType>
			    <xs:restriction base="xs:string">
			      <xs:minLength value="4"/>
			      <xs:maxLength value="9"/>
			    </xs:restriction>
			  </xs:simpleType>
			</xs:element>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="lastname" type="xs:string"/>
			<xs:element name="phone">
			 <xs:simpleType>
			    <xs:restriction base="xs:integer">
			      <xs:pattern value="[6][0-9]{8}"/>
			    </xs:restriction>
			  </xs:simpleType>
			</xs:element>
			<xs:element name="dateborn" type="xs:date"/>
			<xs:element name="gender">
			  <xs:simpleType>
			    <xs:restriction base="xs:string">
			      <xs:pattern value="male|female"/>
			    </xs:restriction>
			  </xs:simpleType>
			</xs:element>
			<xs:element name="mark">
			 <xs:simpleType>
			    <xs:restriction base="xs:integer">
			      <xs:minInclusive value="0"/>
			      <xs:maxInclusive value="10"/>
			    </xs:restriction>
			  </xs:simpleType>
			 </xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== resuadam2/AD/ADTema2Ejer1/bin/Personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<persona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Persona.xsd">
	<nickname>example</nickname>
	<name>Example</name>
	<lastname>First</lastname>
	<phone>654987321</phone>
	<dateborn>1958-05-14</dateborn>
	<gender>female</gender>
	<mark>9</mark>
</persona>
